### ISSUE TITLE
infografia evelin lizeth hernandez

### ISSUE THREAD

**Issue by Eve-lizet** [SistemasTecTlaxiaco/actividad-1-infografia-Eve-Her#2]
[INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Eve-Her/files/12490084/INFOGRAFIA.pdf)

**Comment by Arlet04** [comment]
Partes de la infografía : 3
Coherencia: 3 
Organización: 2
Diseño: 3
Creatividad : 3
Calificación 14/20

**Comment by josealfredo79** [comment]
Falta mejorar un poco mas el trabajo...
